### ISSUE TITLE
input-text-postcode isn't a thing

### ISSUE THREAD

**Issue by JoeChapman** [UKHomeOffice/passports-template-mixins#23]
The docs include `input-text-postcode` in the list of available mustache mixins, however, on investigation, it doesn't appear to a thing. Am I being an idiot, or is not an available mustache mixin?

**Comment by lennym** [comment]
Looks like it's not a thing. We use `{{#input-text-code}}` for postcode input. 

No idea why this changed/is inconsistent. Feel free to either alias the above to `input-text-postcode` or update the docs.

**Comment by lennym** [comment]
https://github.com/UKHomeOffice/passports-template-mixins/commit/bae6d7c8154cd3ce6fa8b9276f6b6ff326457b66
