### ISSUE TITLE
Hint text for select fields

### ISSUE THREAD

**Issue by teneightfive** [UKHomeOffice/passports-template-mixins#51]
The current [select partial](https://github.com/UKHomeOffice/passports-template-mixins/blob/master/partials/forms/select.html) doesn't include the option to add hint text.

**Comment by gavboulton** [comment]
Thanks @teneightfive. PRs welcome.

**Comment by teneightfive** [comment]
@gavboulton Yep, hoping to solve the problem with our app and submit one.

**Comment by teneightfive** [comment]
@gavboulton when you get a chance have a look at #52 which should fix this.
