### ISSUE TITLE
Conditional inputs on radio groups

### ISSUE THREAD

**Issue by teneightfive** [UKHomeOffice/passports-template-mixins#53]
Would be useful to have a way to add conditional fields inside a radio group and more specifically after that option in the group.

Not sure if there is currently a way to achieve this?

**Comment by gavboulton** [comment]
There's not at the moment unfortunately.

**Comment by teneightfive** [comment]
I started to work on a solution for this but not sure it was actually worthwhile. Feels like there might be better ways to achieve the need. Having lots of conditional fields inside a radio group made it feel very jumpy. 

Could close this issue and suggest alternative solutions are considered instead? 

For example:
* Display conditional input on a following step
* Re-evaluate list of options
* Have conditional input always display after all options

**Comment by gavboulton** [comment]
@teneightfive Some work has been done to allow children of radio groups and checkboxes. Partials, form groups and custom HTML can be added. Have a look at https://github.com/UKHomeOffice/passports-template-mixins/commit/cd6f6136b5ed6fc24a5be820cf429785b9e0962b and https://github.com/UKHomeOffice/passports-template-mixins/commit/8003cf99c2466675b59d0c7d444f9ef2c8af653e.

Do these help with your issue?
