### ISSUE TITLE
file mixin

### ISSUE THREAD

**Issue by JoeChapman** [UKHomeOffice/passports-template-mixins#60]
We have a use case for a file type input field `<input type="file">`
https://www.w3.org/TR/html-markup/input.file.html

**Comment by JoeChapman** [comment]
- [ ] input file partial
- [ ] accessible
- [ ] works without js
- [ ] file form data handled by controller
- [ ] accepts valid types

**Comment by gavboulton** [comment]
We'll also need to consider single/multiple files. Drag 'n' drop would be nice to have.
