### ISSUE TITLE
add checkbox-group mixin

### ISSUE THREAD

**Issue by joefitter** [UKHomeOffice/passports-template-mixins#72]
We have a requirement for a checkbox group which displays in the same way as a radio-group. This includes a set of checkboxes within a fieldset described by a legend.  Currently we don't allow multiple values to be associated with a field so this will also require a change in formatting and validation within hmpo-form-controller

**Comment by gavboulton** [comment]
@oli-weighell2 has prototyped something for this so maybe we can move it into the module properly if it's needed elsewhere.
